<?php
/*
 *   Jamshidbek Akhlidinov
 *   26 - 11 2023 8:44:42
 *   https://github.com/JamshidbekAkhlidinov
 */

namespace app\modules\bot\controllers;


use Yii;
use yii\web\Controller;
use yii\web\Response;
use zafarjonovich\Telegram\BotApi;
use zafarjonovich\Telegram\Keyboard;
use zafarjonovich\Telegram\update\objects\Chat;
use zafarjonovich\Telegram\update\Update;

class BotController extends Controller
{
    public $enableCsrfValidation = false;

    public ?BotApi $botApi;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
        Yii::$app->language = 'uz';
    }

    public function initVariables()
    {
        $this->botApi = new BotApi("6754098026:AAFlXf14Ieu-9x3WoNEfd31O4TizGSXNvLA");
        $this->botApi->update = new Update($this->botApi->getWebHookUpdate());
        $this->botApi->invokeUpdates();
        return true;
    }

    public function actionIndex()
    {
        $this->initVariables();
        $update = $this->botApi->update;

        try {
            if ($update->isMessage()) {
                $message = $update->getMessage();
                $type = $message->getChat()->getType();
                $text = $message->isText() ? $message->getText() : '';
                $userProfile = $message->getFrom();
                $bot = $this->botApi;
                $user_id = $bot->from_id;

                if ($message->isFrom() && $type == Chat::TYPE_PRIVATE) {
                    $data = file_get_contents("data/value.txt");
                    $array = explode(",", $data);

                    if ($text == "/start" || $text == "Ortga") {
                        $menuKeyBoard = new Keyboard();
                        $menuKeyBoard->addCustomButton("Miqdor");
                        $menuKeyBoard->addCustomButton("O'rtacha qiymat");
                        $menuKeyBoard->newRow();
                        $menuKeyBoard->addCustomButton("Qurilmalar");
                        $text_message = "Assalomu alaykum. Botimizga hush kelibsiz.";
                        $bot->sendMessage($user_id, $text_message, [
                            'reply_markup' => $menuKeyBoard->init()
                        ]);
                    } elseif ($text == "Miqdor") {
                        $text_message = "Temperatura: {$array[0]}C\n";
                        $text_message .= "Havo namligi: {$array[1]}%\n";
                        $text_message .= "Tuproq namligi: {$array[2]}%\n";
                        $bot->sendMessage($user_id, $text_message);
                    } elseif ($text == "Qurilmalar") {
                        $nasos = "Ochiq";
                        $vent = "Yoniq";
                        $tomchi = "Ochiq";
                        if (isset($array[7])) {
                            if (($array[4] == "N")) {
                                $nasos = "Yoniq";
                            }
                            if (($array[4] == "n")) {
                                $nasos = "O'chiq";
                            }
                        } else {
                            $nasos = "O'chiq";
                        }
                        if (isset($array[7])) {
                            if (($array[5] == "V")) {
                                $vent = "Yoniq";
                            }
                            if (($array[5] == "v")) {
                                $vent = "O'chiq";
                            }
                        } else {
                            $vent = "O'chiq";
                        }


                        if (isset($array[7])) {
                            if (($array[7] == "T")) {
                                $tomchi = "Yoniq";
                            }
                            if (($array[7] == "t")) {
                                $tomchi = "O'chiq";
                            }
                        } else {
                            $tomchi = "O'chiq";
                        }

                        $text_message = "Nasos: " . $nasos . "\n";
                        $text_message .= "Ventilyator: " . $vent . "\n";
                        $text_message .= "Tomchiliab sug'orish: " . $tomchi . "\n";
                        $bot->sendMessage($user_id, $text_message);

                    } elseif ($text == "O'rtacha qiymat") {
                        $text_message = "Temperatura: 20C < x < 27C\n";
                        $text_message .= "Havo namligi: 45% < x < 60%\n";
                        $text_message .= "Tuproq namligi: 23% < x  < 40%\n";
                        $bot->sendMessage($user_id, $text_message);
                    }

                }
            }
        } catch (\Exception $exception) {
            print_r($exception);
            return false;
        }
        return "Success running Bot";
    }
}